# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AdminUser.create(:email => 'admin@example.com', :password => 'admin', :password_confirmation => 'admin')
AdminUser.create(:email => 'edward.w.roman@gmail.com', :password => 'admin', :password_confirmation => 'admin')
AdminUser.create(:email => 'janetz@gmail.com', :password => 'admin', :password_confirmation => 'admin')
AdminUser.create(:email => 'acylum@gmail.com', :password => 'admin', :password_confirmation => 'admin')

# Base seed users for testing
User.create(first_name: 'Ed', email: 'edward.w.roman@gmail.com', phone: '+1 512-773-5555', password: 'admin')
User.create(first_name: 'Janet', email: 'janetz@gmail.com', phone: '+1 650-766-0778', password: 'admin')
User.create(first_name: 'Cyrus', email: 'acylum@gmail.com', phone: '+1 512-423-1532', password: 'admin')

# For SMS testing
User.create(first_name: 'Ed Test', email: 'ed@ghostfiregames.com', phone: '+1 512-773-5555', password: 'admin')
User.create(first_name: 'Janet Test', email: 'janet@improvtest.com', phone: '+1 650-766-0778', password: 'admin')
User.create(first_name: 'Cyrus Test', email: 'cyrus@improvtest.com', phone: '+1 512-423-1532', password: 'admin')

Noun.create(name: 'pilot')
Noun.create(name: 'hiatus')
Noun.create(name: 'kiosk')
Noun.create(name: 'pirate')
Noun.create(name: 'snafu')
Noun.create(name: 'puppet')
Noun.create(name: 'donkey')
Noun.create(name: 'sword')
Noun.create(name: 'teacher')
Noun.create(name: 'banana')
Noun.create(name: 'cupcake')
Noun.create(name: 'airplane')
Noun.create(name: 'rabbit')
Noun.create(name: 'stroller')
Noun.create(name: 'umbrella')
Noun.create(name: 'lotion')
Noun.create(name: 'toilet')
Noun.create(name: 'squirrel')
Noun.create(name: 'cookie')
Noun.create(name: 'potato')
Noun.create(name: 'monkey')
Noun.create(name: 'peacock')
Noun.create(name: 'parakeet')
Noun.create(name: 'bungalo')
Noun.create(name: 'carnival')
Noun.create(name: 'unicorn')
Noun.create(name: 'mustache')
Noun.create(name: 'blubber')
Noun.create(name: 'nosehair')
Noun.create(name: 'razzmatazz')
Noun.create(name: 'flashlight')
Noun.create(name: 'trombone')
Noun.create(name: 'cabbage')
Noun.create(name: 'feather')
Noun.create(name: 'reward')
Noun.create(name: 'pocket')
Noun.create(name: 'quicksand')
Noun.create(name: 'scarecrow')
Noun.create(name: 'throne')
Noun.create(name: 'toothpaste')
Noun.create(name: 'elbow')
Noun.create(name: 'fireman')
Noun.create(name: 'eggnog')
Noun.create(name: 'icicle')
Noun.create(name: 'winner')
Noun.create(name: 'playground')
Noun.create(name: 'honey')
Noun.create(name: 'earthquake')
Noun.create(name: 'mitten')
Noun.create(name: 'wilderness')
Noun.create(name: 'zoo')
Noun.create(name: 'skyscraper')
Noun.create(name: 'captain')
Noun.create(name: 'unicorn')
Noun.create(name: 'zipper')
Noun.create(name: 'superstitious')
Noun.create(name: 'horoscope')
Noun.create(name: 'ninja')
Noun.create(name: 'rainbow')
Noun.create(name: 'gnome')
Noun.create(name: 'dragon')
Noun.create(name: 'stick figure')
Noun.create(name: 'jellybean')
Noun.create(name: 'glitter')
Noun.create(name: 'polka dotted')
Noun.create(name: 'ferris wheel')
Noun.create(name: 'hot dog')
Noun.create(name: 'jet ski')
Noun.create(name: 'banjo')
Noun.create(name: 'hot air balloon')
Noun.create(name: 'trampoline')
Noun.create(name: 'carousel')
Noun.create(name: 'opera singer')
Noun.create(name: 'circus')
Noun.create(name: 'gullible')
Noun.create(name: 'Barney')
Noun.create(name: 'Obama')
Noun.create(name: 'Big Bird')
Noun.create(name: 'Martha Stewart')
Noun.create(name: 'Arnold Schwarzenegger')
Noun.create(name: 'Madonna')
Noun.create(name: 'Jamaica')
Noun.create(name: 'Antarctica')
Noun.create(name: 'Chuck Norris')
Noun.create(name: 'Elvis')
Noun.create(name: 'Tom Hanks')
Noun.create(name: 'Mother Teresa')
Noun.create(name: 'The Beatles')
Noun.create(name: 'Justin Bieber')
Noun.create(name: 'Lady Gaga')
Noun.create(name: 'Chia Pet')
Noun.create(name: 'Paris')
Noun.create(name: 'Charlie Sheen')
Noun.create(name: 'George Foreman Grill')
Noun.create(name: 'Tinkerbell')
Noun.create(name: 'Superman')
Noun.create(name: 'Batman and Robin')
Noun.create(name: 'Kermit the Frog')
Noun.create(name: 'Red Bull')
Verb.create(name: 'bang')
Verb.create(name: 'boom')
Verb.create(name: 'burp')
Verb.create(name: 'charged')
Verb.create(name: 'chase')
Verb.create(name: 'croak')
Verb.create(name: 'discovered')
Verb.create(name: 'douse')
Verb.create(name: 'explode')
Verb.create(name: 'growl')
Verb.create(name: 'hoist')
Verb.create(name: 'jingled')
Verb.create(name: 'lick')
Verb.create(name: 'lunge')
Verb.create(name: 'moo')
Verb.create(name: 'nick')
Verb.create(name: 'paddled')
Verb.create(name: 'panic')
Verb.create(name: 'parachuted')
Verb.create(name: 'peck')
Verb.create(name: 'play')
Verb.create(name: 'plunge')
Verb.create(name: 'pose')
Verb.create(name: 'pout')
Verb.create(name: 'propel')
Verb.create(name: 'pry')
Verb.create(name: 'pump')
Verb.create(name: 'purr')
Verb.create(name: 'quack')
Verb.create(name: 'race')
Verb.create(name: 'raid')
Verb.create(name: 'rally')
Verb.create(name: 'rattle')
Verb.create(name: 'rave')
Verb.create(name: 'resist')
Verb.create(name: 'reveal')
Verb.create(name: 'roar')
Verb.create(name: 'salute')
Verb.create(name: 'scuffle')
Verb.create(name: 'shake')
Verb.create(name: 'shield')
Verb.create(name: 'shiver')
Verb.create(name: 'shock')
Verb.create(name: 'shovel')
Verb.create(name: 'slide')
Verb.create(name: 'slurp')
Verb.create(name: 'snatch')
Verb.create(name: 'snoop')
Verb.create(name: 'splatter')
Verb.create(name: 'sprint')
Verb.create(name: 'squeak')
Verb.create(name: 'startle')
Verb.create(name: 'swagger')
Verb.create(name: 'swerve')
Verb.create(name: 'swim')
Verb.create(name: 'tangled')
Verb.create(name: 'target')
Verb.create(name: 'tickle')
Verb.create(name: 'tucked')
Verb.create(name: 'twist')
Verb.create(name: 'undo')
Verb.create(name: 'vanish')
Verb.create(name: 'vented')
Verb.create(name: 'wandered')
Verb.create(name: 'waved')
Verb.create(name: 'wedge')
Verb.create(name: 'wham')
Verb.create(name: 'whirled')
Verb.create(name: 'whistle')
Verb.create(name: 'wiggle')
Verb.create(name: 'wrecked')
Verb.create(name: 'yanked')
Verb.create(name: 'yelp')
Verb.create(name: 'poke')
Verb.create(name: 'zap')
Verb.create(name: 'enchanted')
Verb.create(name: 'valuable')
Verb.create(name: 'unusual')
Verb.create(name: 'zany')
Verb.create(name: 'grumpy')
Verb.create(name: 'carefree')
Verb.create(name: 'jolly')
Verb.create(name: 'rowdy')
Verb.create(name: 'velvety')
Verb.create(name: 'glossy')
Verb.create(name: 'lumpy')
Verb.create(name: 'scrawny')
Verb.create(name: 'frozen')
Verb.create(name: 'fiery')
Verb.create(name: 'antique')
Verb.create(name: 'winding')
Verb.create(name: 'shimmering')
Verb.create(name: 'tanned')
Verb.create(name: 'swinging')
Verb.create(name: 'dirty')
Verb.create(name: 'useless')
Verb.create(name: 'witty')
Verb.create(name: 'thunderous')
Verb.create(name: 'whispered')
Verb.create(name: 'sweet')
Verb.create(name: 'spicy')
Verb.create(name: 'sassy')
Verb.create(name: 'polyester')
Verb.create(name: 'rainbow')
Verb.create(name: 'clumsy')
Verb.create(name: 'hissing')
Verb.create(name: 'victorious')
Verb.create(name: 'narrow')
Verb.create(name: 'teeny-tiny')
Verb.create(name: 'mysterious')
Verb.create(name: 'itchy')
Verb.create(name: 'colossal')
Verb.create(name: 'curious')
Verb.create(name: 'husky')
Verb.create(name: 'crooked')
Verb.create(name: 'stale')
Verb.create(name: 'courageous')
Verb.create(name: 'tender')
Verb.create(name: 'greasy')
Verb.create(name: 'grubby')
Verb.create(name: 'nutty')
Verb.create(name: 'ancient')
Verb.create(name: 'lucky')
Verb.create(name: 'breezy')
Intro.create(name: 'Once upon a time, we were walking through the forest...')
Intro.create(name: 'In a land that time forgot...')
Intro.create(name: 'In the not-too-distant future...')
Intro.create(name: 'Back in the day...')
Intro.create(name: 'It was a dark and stormy night...')
Intro.create(name: 'In a galaxy far far away...')
Intro.create(name: 'If we could create an infomercial...')