# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AdminUser.create(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')
AdminUser.create(:email => 'edward.w.roman@gmail.com', :password => 'password', :password_confirmation => 'password')
AdminUser.create(:email => 'janetz@gmail.com', :password => 'password', :password_confirmation => 'password')
AdminUser.create(:email => 'acylum@gmail.com', :password => 'password', :password_confirmation => 'password')
User.create(first_name: 'Ed', email: 'edward.w.roman@gmail.com', phone: '123-456-7890', password: '')
User.create(first_name: 'Janet', email: 'janetz@gmail.com', phone: '123-456-7890', password: '')
User.create(first_name: 'Cyrus', email: 'acylum@gmail.com', phone: '123-456-7890', password: '')
Noun.create(name: 'zebra')
Noun.create(name: 'statue')
Noun.create(name: 'gladiator')
Noun.create(name: 'blanket')
Noun.create(name: 'Michael Jordan')
Noun.create(name: 'paperweight')
Noun.create(name: 'goldfish')
Noun.create(name: 'bathroom')
Noun.create(name: 'destruction')
Noun.create(name: 'discover')
Verb.create(name: 'shriek')
Verb.create(name: 'whisper')
Verb.create(name: 'urinate')
Verb.create(name: 'peep')
Verb.create(name: 'punch')
Verb.create(name: 'fled')
Verb.create(name: 'shuffle')
Verb.create(name: 'peep')
Verb.create(name: 'urinate')
Verb.create(name: 'growl')
Intro.create(name: 'Once upon a time, we were walking through the forest...')
Intro.create(name: 'In a land that time forgot...')
Intro.create(name: 'In the not-too-distant future...')